version: "3.9"

services:
  pulse-client:
    build: .
    container_name: pulse-client
    pid: host
    env_file:
      - .env
    environment:
      NODE_ENV: production
      INCLUDE_DOCKER_CONTAINERS: "true"
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
